<?php
// ============================================================
// ULMS — Configuration TEMPLATE
// app/config/config.example.php
//
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY.
//     Copy this file to config.php and fill in your values:
//
//     cp app/config/config.example.php app/config/config.php
//
//     config.php is listed in .gitignore and will NOT be
//     committed to the repository.
// ============================================================

// ── Database credentials ─────────────────────────────────────
define('DB_HOST',    'localhost');
define('DB_PORT',    '3306');
define('DB_NAME',    'ulms_db');          // ← your database name
define('DB_USER',    'root');             // ← your MySQL username
define('DB_PASS',    '');                 // ← your MySQL password
define('DB_CHARSET', 'utf8mb4');

// ── Application settings ─────────────────────────────────────
define('APP_NAME',    'University Library Management System');
define('APP_SHORT',   'ULMS');
define('APP_URL',     'http://localhost/library-system/public'); // ← your base URL
define('APP_VERSION', '1.0.0');
define('WEB_BASE',    '/library-system'); // ← server-root path prefix

// ── Fine & Loan settings ─────────────────────────────────────
define('FINE_PER_DAY',     10.00);  // Rs. per overdue day
define('LOAN_PERIOD_DAYS', 14);     // borrowing period in days

// ── Session ──────────────────────────────────────────────────
define('SESSION_NAME',     'ulms_session');
define('SESSION_LIFETIME', 3600); // seconds (1 hour)

// ── Date / Time ──────────────────────────────────────────────
define('DATE_FORMAT',     'd M Y');
define('DATETIME_FORMAT', 'd M Y H:i');
date_default_timezone_set('Asia/Colombo'); // ← your timezone

// ── Error display ────────────────────────────────────────────
define('DEBUG_MODE', true); // set false in production
if (DEBUG_MODE) {
    ini_set('display_errors', 1);
    error_reporting(E_ALL);
} else {
    ini_set('display_errors', 0);
    error_reporting(0);
}
